"""
00_generate_synthetic_data.py
Project: Immunization Compliance Analytics Dashboard
Author: Aly Drame, MD, MPH, MBA

IMPORTANT: All data generated by this script are entirely synthetic.
No real provider data, no CDC program records, and no personally
identifiable information are included. This dataset was created for
portfolio demonstration purposes only.

The statistical distributions used (compliance rates, unenrollment
rates, domain failure rates) are informed by publicly available
academic literature and CDC program descriptions, not by any
internal or restricted CDC data.
"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random
import os

# ── reproducibility ────────────────────────────────────────────────
np.random.seed(42)
random.seed(42)

# ── output directory ───────────────────────────────────────────────
os.makedirs('data/synthetic', exist_ok=True)
os.makedirs('data/processed', exist_ok=True)
os.makedirs('outputs',        exist_ok=True)

# ══════════════════════════════════════════════════════════════════
# TABLE 1 — PROVIDERS
# ══════════════════════════════════════════════════════════════════

N_PROVIDERS = 1000

provider_types = [
    'Pediatrics', 'Family Medicine', 'Internal Medicine',
    'Pharmacy', 'Community Health Center', 'Hospital Clinic', 'OB/GYN'
]
provider_type_weights = [0.28, 0.25, 0.15, 0.12, 0.10, 0.07, 0.03]

jurisdictions = [
    'GA', 'FL', 'TX', 'NY', 'CA', 'OH', 'PA', 'IL', 'NC', 'AZ',
    'MI', 'WA', 'CO', 'MN', 'TN'
]

practice_sizes  = ['1-2', '3-5', '6-10', '11+']
practice_weights = [0.30,  0.35,  0.25,   0.10]

enrollment_years = [2019, 2020, 2021, 2022, 2023]

providers = pd.DataFrame({
    'provider_id': [f'PRV{str(i).zfill(5)}' for i in range(1, N_PROVIDERS + 1)],
    'vfc_pin':     [f'VFC-{str(i).zfill(5)}' for i in range(1, N_PROVIDERS + 1)],
    'provider_type': np.random.choice(
        provider_types, N_PROVIDERS, p=provider_type_weights),
    'jurisdiction_id': np.random.choice(jurisdictions, N_PROVIDERS),
    'urban_rural': np.random.choice(
        ['Urban', 'Suburban', 'Rural'], N_PROVIDERS, p=[0.50, 0.30, 0.20]),
    'practice_size': np.random.choice(
        practice_sizes, N_PROVIDERS, p=practice_weights),
    'enrollment_year': np.random.choice(enrollment_years, N_PROVIDERS),
    'months_enrolled': np.random.randint(6, 61, N_PROVIDERS),
    'active_flag': 'Y'   # will be updated when unenrollments are assigned
})

print(f"[TABLE 1] providers — {len(providers):,} rows")

# ══════════════════════════════════════════════════════════════════
# TABLE 2 — VISITS
# ══════════════════════════════════════════════════════════════════
# Each provider receives 2–6 visits over the observation window
# (2022-01-01 through 2024-12-31).
# This mirrors a real VFC program where providers are visited at
# least annually and sometimes more frequently if noncompliant.

def random_date(start: datetime, end: datetime) -> datetime:
    delta = end - start
    return start + timedelta(days=random.randint(0, delta.days))

visit_start = datetime(2022, 1, 1)
visit_end   = datetime(2024, 12, 31)

ca_types = ['None', 'Education', 'Warning Letter', 'Suspension']
ca_weights = [0.70, 0.20, 0.08, 0.02]

staff_types = ['VFC Coordinator', 'State Immunization Staff', 'Federal Staff']
staff_weights = [0.65, 0.30, 0.05]

visit_rows = []
for _, provider in providers.iterrows():
    n_visits = np.random.randint(2, 7)   # 2–6 visits per provider
    for _ in range(n_visits):
        vdate = random_date(visit_start, visit_end)

        # Baseline compliance probability influenced by provider type
        # (mirrors published literature — pharmacies and large hospital
        # clinics tend to have higher compliance rates)
        base_compliance = {
            'Pediatrics': 0.84,
            'Family Medicine': 0.82,
            'Internal Medicine': 0.80,
            'Pharmacy': 0.88,
            'Community Health Center': 0.78,
            'Hospital Clinic': 0.86,
            'OB/GYN': 0.79
        }.get(provider['provider_type'], 0.82)

        # Rural providers have slightly lower compliance on average
        if provider['urban_rural'] == 'Rural':
            base_compliance -= 0.05
        elif provider['urban_rural'] == 'Suburban':
            base_compliance -= 0.02

        compliant = 'Y' if random.random() < base_compliance else 'N'

        # Domain failures are more likely when overall noncompliant
        domain_fail_prob = 0.08 if compliant == 'Y' else 0.40

        def domain(fail_prob, missing_prob):
            if random.random() < missing_prob:
                return None
            return 'N' if random.random() < fail_prob else 'Y'

        # Corrective action: only issued when noncompliant
        ca_issued = 'N'
        ca_type   = 'None'
        if compliant == 'N' and random.random() < 0.60:
            ca_issued = 'Y'
            ca_type = np.random.choice(
                ['Education', 'Warning Letter', 'Suspension'],
                p=[0.65, 0.28, 0.07]
            )

        # Helpdesk tickets: Poisson-distributed, higher when noncompliant
        tickets_lambda = 0.8 if compliant == 'Y' else 2.5
        tickets = min(int(np.random.poisson(tickets_lambda)), 10)

        visit_rows.append({
            'visit_id_placeholder': None, # assigned after all rows created
            'provider_id': provider['provider_id'],
            'visit_date': vdate.strftime('%Y-%m-%d'),
            'visit_year': vdate.year,
            'visit_quarter': (vdate.month - 1) // 3 + 1,
            'compliant_flag': None if random.random() < 0.03 else compliant,
            'domain_storage':
                domain(domain_fail_prob * 1.2, 0.05),
            'domain_temperature':
                domain(domain_fail_prob * 1.1, 0.05),
            'domain_documentation':
                domain(domain_fail_prob * 0.9, 0.04),
            'domain_inventory':
                domain(domain_fail_prob * 0.8, 0.04),
            'domain_patient_eligibility':
                domain(domain_fail_prob * 0.7, 0.05),
            'corrective_action_issued':
                None if random.random() < 0.02 else ca_issued,
            'corrective_action_type':
                ca_type if ca_issued == 'Y' else None,
            'helpdesk_tickets': tickets,
            'visit_type': np.random.choice(
                ['Scheduled', 'Unannounced'], p=[0.75, 0.25]),
            'staff_conducting': np.random.choice(
                staff_types, p=staff_weights)
        })

visits = pd.DataFrame(visit_rows)
visits.insert(0, 'visit_id',
    [f'VIS{str(i).zfill(6)}' for i in range(1, len(visits) + 1)])

print(f"[TABLE 2] visits — {len(visits):,} rows "
      f"across {visits['provider_id'].nunique():,} providers")

# ══════════════════════════════════════════════════════════════════
# TABLE 3 — UNENROLLMENTS
# Approximately 15% of providers unenroll over the observation window.
# ══════════════════════════════════════════════════════════════════

# Select providers to unenroll — weighted toward noncompliant ones
provider_compliance_rates = (
    visits.dropna(subset=['compliant_flag'])
    .groupby('provider_id')['compliant_flag']
    .apply(lambda x: (x == 'Y').mean())
    .reset_index()
    .rename(columns={'compliant_flag': 'compliance_rate'})
)
providers = providers.merge(provider_compliance_rates, on='provider_id', how='left')
providers['compliance_rate'] = providers['compliance_rate'].fillna(0.82)

# Probability of unenrollment inversely related to compliance rate
providers['unenrollment_prob'] = (
    0.05 + (1 - providers['compliance_rate']) * 0.40
)

unenrolled_mask = (
    np.random.random(N_PROVIDERS) < providers['unenrollment_prob']
)
unenrolled_providers = providers[unenrolled_mask].copy()

print(f"[TABLE 3] unenrollments — {len(unenrolled_providers):,} providers "
      f"({len(unenrolled_providers)/N_PROVIDERS:.1%} unenrollment rate)")

reasons = [
    'Practice Closed', 'Compliance Failure',
    'Voluntary Withdrawal', 'Relocation', 'Unknown'
]
reason_weights = [0.20, 0.35, 0.25, 0.12, 0.08]

unenrollment_rows = []
for i, (_, p) in enumerate(unenrolled_providers.iterrows()):
    months_to_unenroll = np.random.randint(3, 49)
    unenroll_date = visit_start + timedelta(days=months_to_unenroll * 30)
    if unenroll_date > visit_end:
        unenroll_date = visit_end

    reason = np.random.choice(reasons, p=reason_weights)
    if random.random() < 0.08:
        reason = None    # 8% missing reason

    unenrollment_rows.append({
        'unenrollment_id': f'UEN{str(i + 1).zfill(6)}',
        'provider_id': p['provider_id'],
        'unenrollment_date': unenroll_date.strftime('%Y-%m-%d'),
        'months_to_unenrollment': months_to_unenroll,
        'unenrollment_reason': reason,
        'initiated_by': np.random.choice(
            ['Provider', 'Program Staff', 'Automated'],
            p=[0.40, 0.50, 0.10])
    })

unenrollments = pd.DataFrame(unenrollment_rows)

# Update active_flag in providers table
providers['active_flag'] = np.where(
    providers['provider_id'].isin(unenrollments['provider_id']), 'N', 'Y'
)
# Add binary unenrolled flag for modeling
providers['unenrolled_flag'] = np.where(
    providers['provider_id'].isin(unenrollments['provider_id']), 'Y', 'N'
)

# Drop the helper column before saving
providers_out = providers.drop(columns=['compliance_rate',
                                         'unenrollment_prob'])

# ══════════════════════════════════════════════════════════════════
# SAVE ALL THREE TABLES
# ══════════════════════════════════════════════════════════════════

providers_out.to_csv('data/synthetic/providers.csv',    index=False)
visits.to_csv(       'data/synthetic/visits.csv',       index=False)
unenrollments.to_csv('data/synthetic/unenrollments.csv', index=False)

# ── summary statistics ─────────────────────────────────────────────
print("\n=== DATASET SUMMARY ===")
print(f"providers.csv      : {len(providers_out):,} rows × "
      f"{len(providers_out.columns)} columns")
print(f"visits.csv         : {len(visits):,} rows × "
      f"{len(visits.columns)} columns")
print(f"unenrollments.csv  : {len(unenrollments):,} rows × "
      f"{len(unenrollments.columns)} columns")

# Compliance rate by provider type
print("\n--- Compliance rate by provider type ---")
cr = (
    visits.dropna(subset=['compliant_flag'])
    .groupby('provider_type' if 'provider_type' in visits.columns
             else 'provider_id')
    .apply(lambda df: (df['compliant_flag'] == 'Y').mean())
)
# merge provider type into visits for this summary
v_with_type = visits.merge(
    providers_out[['provider_id','provider_type']], on='provider_id')
cr = (
    v_with_type.dropna(subset=['compliant_flag'])
    .groupby('provider_type')['compliant_flag']
    .apply(lambda x: f"{(x=='Y').mean():.1%}")
)
print(cr.to_string())

print("\n--- Unenrollment rate by provider type ---")
ue = providers_out.groupby('provider_type')['unenrolled_flag'].apply(
    lambda x: f"{(x=='Y').mean():.1%}")
print(ue.to_string())

print("\n--- Missing value summary (visits) ---")
miss = visits.isnull().mean().mul(100).round(1)
print(miss[miss > 0].to_string())

print("\nAll files saved to data/synthetic/")
